import { createSlice } from "@reduxjs/toolkit";

export const Statuses = {
  Initial: "Not Fetched",
  Loading: "Loading..",
  UpToDate: "Up To Date",
  Deleted: "Deleted",
  Error: "Error",
};

const initialState = {
  start: new Date().toString(),
  end: new Date().toString(),
  description: "",
  position: 0,
  shifts: [],
  status: Statuses.Initial,
};

export const initialShiftState = initialState;

export const shiftSlice = createSlice({
  name: "shift",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    createShift: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.shifts = action.payload;
    },
    resetShifts: (state, action) => {
      state.shifts = [];
      state.start = new Date().toString();
      state.end = new Date().toString();
      state.position = 0;
      state.description = "";
    },
    setStart: (state, action) => {
      state.start = action.payload;
    },
    setEnd: (state, action) => {
      state.end = action.payload;
    },
    setPosition: (state, action) => {
      state.position = action.payload;
    },
    setDescription: (state, action) => {
      console.log("working??");
      state.description = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const {
  createShift,
  deleteShift,
  resetShifts,
  editShift,
  setStart,
  setEnd,
  setPosition,
  setDescription,
} = shiftSlice.actions;

export const selectShifts = (state) => state.shifts.shifts;

export const selectPosition = (state) => state.shifts.position;

export const selectDescription = (state) => state.shifts.description;

export const selectStart = (state) => state.shifts.start;

export const selectEnd = (state) => state.shifts.end;

export default shiftSlice.reducer;
